// <auto-generated />
using System;
using Alfanar.MarketIntel.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Alfanar.MarketIntel.Infrastructure.Migrations
{
    [DbContext(typeof(MarketIntelDbContext))]
    [Migration("20251229053308_AddTagsAndRssFeedEntities")]
    partial class AddTagsAndRssFeedEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.NewsArticle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BodyText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("ClassificationConfidence")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ProcessedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PublishedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("RssFeedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("PublishedUtc");

                    b.HasIndex("RssFeedId");

                    b.HasIndex("Source");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.HasIndex("Category", "Region");

                    b.ToTable("NewsArticles");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.NewsArticleTag", b =>
                {
                    b.Property<Guid>("NewsArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("NewsArticleId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("NewsArticleTags");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.RssFeed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastETag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastFetchedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModified")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("RssFeeds");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.NewsArticle", b =>
                {
                    b.HasOne("Alfanar.MarketIntel.Domain.Entities.RssFeed", "RssFeed")
                        .WithMany("Articles")
                        .HasForeignKey("RssFeedId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RssFeed");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.NewsArticleTag", b =>
                {
                    b.HasOne("Alfanar.MarketIntel.Domain.Entities.NewsArticle", "NewsArticle")
                        .WithMany("NewsArticleTags")
                        .HasForeignKey("NewsArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alfanar.MarketIntel.Domain.Entities.Tag", "Tag")
                        .WithMany("NewsArticleTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewsArticle");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.NewsArticle", b =>
                {
                    b.Navigation("NewsArticleTags");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.RssFeed", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.Tag", b =>
                {
                    b.Navigation("NewsArticleTags");
                });
#pragma warning restore 612, 618
        }
    }
}
