// <auto-generated />
using System;
using Alfanar.MarketIntel.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Alfanar.MarketIntel.Infrastructure.Migrations
{
    [DbContext(typeof(MarketIntelDbContext))]
    [Migration("20260405054052_AddTenderNotificationEnhancements")]
    partial class AddTenderNotificationEnhancements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.CompanyContactInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("HeadquartersAddressLine1")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HeadquartersAddressLine2")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HeadquartersCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HeadquartersCountry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HeadquartersCountryCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("HeadquartersLandmark")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HeadquartersPoBox")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HeadquartersPostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MainPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneAvailabilityDays")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneAvailabilityHours")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneAvailabilityTimezone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SalesEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SupportEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TollFreePhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Company")
                        .IsUnique();

                    b.ToTable("CompanyContactInfo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Company = "alfanar",
                            CreatedAt = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            HeadquartersAddressLine1 = "Al-Nafl - Northern Ring Road",
                            HeadquartersAddressLine2 = "Between Exits 5 & 6",
                            HeadquartersCity = "Riyadh",
                            HeadquartersCountry = "Kingdom of Saudi Arabia",
                            HeadquartersCountryCode = "KSA",
                            HeadquartersLandmark = "Near King Abdulaziz Center for National Dialogue",
                            HeadquartersPoBox = "P.O. Box 301",
                            HeadquartersPostalCode = "11411",
                            MainPhone = "+966 573786035",
                            PhoneAvailabilityDays = "Mon-Fri",
                            PhoneAvailabilityHours = "9AM-6PM",
                            PhoneAvailabilityTimezone = "EST",
                            SalesEmail = "sales@alfanar.com",
                            SupportEmail = "support@alfanar.com",
                            TollFreePhone = "800-124-1333",
                            UpdatedAt = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.CompanyOffice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Building")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BuildingNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CompanyContactInfoId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Floor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OfficeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PoBox")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Street")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Tower")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Country");

                    b.HasIndex("CompanyContactInfoId", "Region");

                    b.ToTable("CompanyOffices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = "alfanar Industrial City",
                            Building = "Sales and Marketing Building",
                            CompanyContactInfoId = 1,
                            Country = "Saudi Arabia",
                            CreatedAt = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            OfficeType = "Sales and Marketing",
                            Region = "Saudi Arabia",
                            UpdatedAt = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            City = "Madrid",
                            CompanyContactInfoId = 1,
                            Country = "Spain",
                            CreatedAt = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            OfficeType = "Regional Office",
                            Region = "Europe",
                            UpdatedAt = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CompanyContactInfoId = 1,
                            CompanyName = "alfanar Electrical Systems LLC",
                            Country = "United Arab Emirates",
                            CreatedAt = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            OfficeType = "Subsidiary",
                            Region = "UAE",
                            UpdatedAt = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Area = "DLF Cybercity, Phase-3",
                            BuildingNumber = "Building No. 5",
                            City = "Gurgaon",
                            CompanyContactInfoId = 1,
                            Country = "India",
                            CreatedAt = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = "15th Floor",
                            OfficeType = "Regional Office",
                            Region = "India",
                            Tower = "Tower B",
                            UpdatedAt = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Area = "Sheraton Al Matar",
                            City = "Cairo",
                            CompanyContactInfoId = 1,
                            Country = "Egypt",
                            CreatedAt = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "El Nozha",
                            OfficeType = "Regional Office",
                            PoBox = "P.O. Box 11736",
                            Region = "Egypt",
                            Street = "181 El-Orouba St",
                            UpdatedAt = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.Competitor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAutoDetected")
                        .HasColumnType("bit");

                    b.Property<string>("Keywords")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsAutoDetected");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Competitors");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.CompetitorMention", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompetitorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DetectedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAutoDetected")
                        .HasColumnType("bit");

                    b.Property<string>("MentionContext")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SentimentLabel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("SentimentScore")
                        .HasColumnType("float");

                    b.Property<string>("Snippet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("CompetitorId");

                    b.HasIndex("DetectedUtc");

                    b.HasIndex("SourceId");

                    b.HasIndex("SourceType");

                    b.ToTable("CompetitorMentions");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.ContactFormSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RespondedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ResponseMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("IsRead");

                    b.HasIndex("Status");

                    b.HasIndex("SubmittedAt");

                    b.ToTable("ContactFormSubmissions");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.FinancialMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Change")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ChangePercent")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("float");

                    b.Property<DateTime>("ExtractedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExtractionMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("FinancialReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MetricType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Period")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("PreviousValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("SourceText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Value")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("FinancialReportId");

                    b.HasIndex("MetricType");

                    b.ToTable("FinancialMetrics");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.FinancialReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DownloadUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FiscalQuarter")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("FiscalYear")
                        .HasColumnType("int");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PageCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ProcessedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("RequiredOcr")
                        .HasColumnType("bit");

                    b.Property<string>("Sector")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyName");

                    b.HasIndex("IsProcessed");

                    b.HasIndex("ProcessingStatus");

                    b.HasIndex("PublishedDate");

                    b.HasIndex("ReportType");

                    b.HasIndex("SourceUrl")
                        .IsUnique();

                    b.HasIndex("FiscalYear", "FiscalQuarter");

                    b.ToTable("FinancialReports");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.FinancialReportTag", b =>
                {
                    b.Property<Guid>("FinancialReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("FinancialReportId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("FinancialReportTags");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.IntelligenceReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AiModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompetitorUpdates")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("DeduplicatedArticleCount")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ExecutiveSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GeneratedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvestmentsAndFunding")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MaSignals")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("MarketMovements")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("PdfFilePath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PolicyAndRegulation")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<long>("ProcessingTimeMs")
                        .HasColumnType("bigint");

                    b.Property<int>("RawArticleCount")
                        .HasColumnType("int");

                    b.Property<string>("RisksAndOpportunities")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TechnologyDevelopments")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("ToDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TokensUsed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedUtc");

                    b.HasIndex("Keyword");

                    b.HasIndex("Status");

                    b.HasIndex("Keyword", "GeneratedUtc");

                    b.ToTable("IntelligenceReports");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.IntelligenceReportResult", b =>
                {
                    b.Property<Guid>("IntelligenceReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WebSearchResultId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IntelligenceReportId", "WebSearchResultId");

                    b.HasIndex("WebSearchResultId");

                    b.ToTable("IntelligenceReportResults");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.KeywordMonitor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CheckIntervalMinutes")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("LastCheckedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxResultsPerCheck")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Keyword");

                    b.HasIndex("LastCheckedUtc");

                    b.ToTable("KeywordMonitors");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.NewsArticle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BodyText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("ClassificationConfidence")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ProcessedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PublishedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("RelatedFinancialReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RssFeedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("PublishedUtc");

                    b.HasIndex("RelatedFinancialReportId");

                    b.HasIndex("RssFeedId");

                    b.HasIndex("Source");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.HasIndex("Category", "Region");

                    b.ToTable("NewsArticles");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.NewsArticleTag", b =>
                {
                    b.Property<Guid>("NewsArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("NewsArticleId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("NewsArticleTags");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.NotificationPreferences", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AlertTypesToNotify")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<bool>("EmailEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("KeywordsToNotify")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("NotifyOnCritical")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyOnHigh")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyOnMedium")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("EmailEnabled");

                    b.ToTable("NotificationPreferences");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.NotificationQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlertId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AlertId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("NotificationQueues");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.ReportAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AiModel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("AnalysisConfidence")
                        .HasColumnType("float");

                    b.Property<string>("CompetitivePosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExecutiveSummary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinancialMetrics")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FinancialReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InvestmentThesis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeyHighlights")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarketOutlook")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ProcessingTimeMs")
                        .HasColumnType("bigint");

                    b.Property<string>("RelatedEntities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RiskFactors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SentimentLabel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("SentimentScore")
                        .HasColumnType("float");

                    b.Property<string>("StrategicInitiatives")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TokensUsed")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("FinancialReportId")
                        .IsUnique();

                    b.HasIndex("SentimentScore");

                    b.ToTable("ReportAnalyses");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.ReportResult", b =>
                {
                    b.Property<Guid>("ReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WebSearchResultId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReportId", "WebSearchResultId");

                    b.HasIndex("WebSearchResultId");

                    b.ToTable("ReportResults");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.ReportSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<double?>("ExtractionConfidence")
                        .HasColumnType("float");

                    b.Property<Guid>("FinancialReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("KeyDataPoints")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("PageNumbers")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SectionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("FinancialReportId");

                    b.HasIndex("FinancialReportId", "OrderIndex");

                    b.ToTable("ReportSections");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.RssFeed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastETag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastFetchedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModified")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("RssFeeds");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.SmartAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AcknowledgedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ActualValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("AlertSubType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FinancialReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal?>("ThresholdValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TriggerKeywords")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TriggerMetric")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AlertType");

                    b.HasIndex("CompanyName");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FinancialReportId");

                    b.HasIndex("IsAcknowledged");

                    b.HasIndex("Severity");

                    b.HasIndex("SourceId");

                    b.HasIndex("SourceType");

                    b.ToTable("SmartAlerts");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.TechnologyReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeneratedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("GeneratedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("PdfFilePath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TotalResults")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EndDate");

                    b.HasIndex("GeneratedUtc");

                    b.HasIndex("StartDate");

                    b.ToTable("TechnologyReports");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.TenderAiAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExtractedRequirementsJson")
                        .HasMaxLength(16000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("TenderVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TenderVersionId");

                    b.ToTable("TenderAiAnalyses");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.TenderAuditRaw", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RawPayloadJson")
                        .IsRequired()
                        .HasMaxLength(16000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RetentionUntil")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RetrievedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PayloadHash");

                    b.HasIndex("SourceId", "ExternalId", "RetrievedAt");

                    b.ToTable("TenderAuditRaw");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.TenderAuthority", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AliasesJson")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("AuthorityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("NormalizedName");

                    b.HasIndex("CountryId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("TenderAuthorities");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.TenderCapabilityGap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GapLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InternalCapability")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Requirement")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("TenderVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("GapLevel");

                    b.HasIndex("TenderVersionId");

                    b.ToTable("TenderCapabilityGaps");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.TenderCountry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RegionGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsoCode")
                        .IsUnique();

                    b.HasIndex("RegionGroup");

                    b.ToTable("TenderCountries");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.TenderDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DocumentUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("FileHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FileName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FileType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("RetrievedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("StoragePath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("TenderNoticeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenderNoticeId");

                    b.HasIndex("TenderNoticeId", "FileHash");

                    b.ToTable("TenderDocuments");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.TenderIngestionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Errors")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("ItemsFetched")
                        .HasColumnType("int");

                    b.Property<int>("ItemsNew")
                        .HasColumnType("int");

                    b.Property<int>("ItemsUpdated")
                        .HasColumnType("int");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WorkerId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("SourceId", "StartedAt");

                    b.ToTable("TenderIngestionRuns");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.TenderNotice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AuthorityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Currency")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("CurrentVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("EstimatedValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sector")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Summary")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CurrentVersionId");

                    b.HasIndex("IsActive");

                    b.HasIndex("LastChangedAt");

                    b.HasIndex("AuthorityId", "PublishDate");

                    b.HasIndex("CountryId", "PublishDate");

                    b.HasIndex("SourceId", "ExternalId")
                        .IsUnique();

                    b.ToTable("TenderNotices");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.TenderNotificationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DedupKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("NotificationBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenderNoticeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenderVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DedupKey")
                        .IsUnique();

                    b.HasIndex("RuleId");

                    b.HasIndex("SentAt");

                    b.HasIndex("TenderNoticeId");

                    b.HasIndex("TenderVersionId");

                    b.ToTable("TenderNotificationLogs");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.TenderNotificationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorityFilter")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Channels")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CountryFilter")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityFilter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Keywords")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SectorFilter")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("ValueMax")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValueMin")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Scope", "UserId");

                    b.ToTable("TenderNotificationRules");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.TenderScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComponentsJson")
                        .HasMaxLength(16000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("RiskScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("ScoringModel")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("TenderVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("WinProbability")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TenderVersionId");

                    b.ToTable("TenderScores");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.TenderSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthMode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ConnectorConfigJson")
                        .HasMaxLength(16000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCanary")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("LegalNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Owner")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PollIntervalMin")
                        .HasColumnType("int");

                    b.Property<int>("PollPriority")
                        .HasColumnType("int");

                    b.Property<string>("RateLimitPolicyJson")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("RolloutStage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IsCanary");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PollPriority");

                    b.HasIndex("RolloutStage");

                    b.ToTable("TenderSources");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.TenderVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ChangedFieldsJson")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RawHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SnapshotJson")
                        .HasMaxLength(16000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenderNoticeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAt");

                    b.HasIndex("TenderNoticeId", "VersionNo")
                        .IsUnique();

                    b.ToTable("TenderVersions");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.TrendSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AverageSentiment")
                        .HasColumnType("float");

                    b.Property<string>("CompetitorMentionCounts")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MentionCount")
                        .HasColumnType("int");

                    b.Property<int>("NewsCount")
                        .HasColumnType("int");

                    b.Property<int>("SignalStrength")
                        .HasColumnType("int");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TopSources")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("WebSearchCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Keyword");

                    b.HasIndex("SnapshotDate");

                    b.HasIndex("Keyword", "SnapshotDate")
                        .IsUnique();

                    b.ToTable("TrendSnapshots");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.WebSearchResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsFromMonitoring")
                        .HasColumnType("bit");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("KeywordMonitorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Metadata")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RetrievedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SearchProvider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Snippet")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("IsFromMonitoring");

                    b.HasIndex("Keyword");

                    b.HasIndex("KeywordMonitorId");

                    b.HasIndex("PublishedDate");

                    b.HasIndex("RetrievedUtc");

                    b.HasIndex("Keyword", "Url")
                        .IsUnique();

                    b.ToTable("WebSearchResults");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.CompanyOffice", b =>
                {
                    b.HasOne("Alfanar.MarketIntel.Domain.Entities.CompanyContactInfo", "CompanyContactInfo")
                        .WithMany("CompanyOffices")
                        .HasForeignKey("CompanyContactInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyContactInfo");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.CompetitorMention", b =>
                {
                    b.HasOne("Alfanar.MarketIntel.Domain.Entities.Competitor", "Competitor")
                        .WithMany("Mentions")
                        .HasForeignKey("CompetitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competitor");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.FinancialMetric", b =>
                {
                    b.HasOne("Alfanar.MarketIntel.Domain.Entities.FinancialReport", "FinancialReport")
                        .WithMany()
                        .HasForeignKey("FinancialReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinancialReport");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.FinancialReportTag", b =>
                {
                    b.HasOne("Alfanar.MarketIntel.Domain.Entities.FinancialReport", "FinancialReport")
                        .WithMany("FinancialReportTags")
                        .HasForeignKey("FinancialReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alfanar.MarketIntel.Domain.Entities.Tag", "Tag")
                        .WithMany("FinancialReportTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinancialReport");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.IntelligenceReportResult", b =>
                {
                    b.HasOne("Alfanar.MarketIntel.Domain.Entities.IntelligenceReport", "IntelligenceReport")
                        .WithMany("ReportResults")
                        .HasForeignKey("IntelligenceReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alfanar.MarketIntel.Domain.Entities.WebSearchResult", "WebSearchResult")
                        .WithMany()
                        .HasForeignKey("WebSearchResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IntelligenceReport");

                    b.Navigation("WebSearchResult");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.NewsArticle", b =>
                {
                    b.HasOne("Alfanar.MarketIntel.Domain.Entities.FinancialReport", "RelatedFinancialReport")
                        .WithMany("RelatedArticles")
                        .HasForeignKey("RelatedFinancialReportId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Alfanar.MarketIntel.Domain.Entities.RssFeed", "RssFeed")
                        .WithMany("Articles")
                        .HasForeignKey("RssFeedId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RelatedFinancialReport");

                    b.Navigation("RssFeed");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.NewsArticleTag", b =>
                {
                    b.HasOne("Alfanar.MarketIntel.Domain.Entities.NewsArticle", "NewsArticle")
                        .WithMany("NewsArticleTags")
                        .HasForeignKey("NewsArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alfanar.MarketIntel.Domain.Entities.Tag", "Tag")
                        .WithMany("NewsArticleTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewsArticle");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.ReportAnalysis", b =>
                {
                    b.HasOne("Alfanar.MarketIntel.Domain.Entities.FinancialReport", "FinancialReport")
                        .WithOne("Analysis")
                        .HasForeignKey("Alfanar.MarketIntel.Domain.Entities.ReportAnalysis", "FinancialReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinancialReport");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.ReportResult", b =>
                {
                    b.HasOne("Alfanar.MarketIntel.Domain.Entities.TechnologyReport", "Report")
                        .WithMany("ReportResults")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alfanar.MarketIntel.Domain.Entities.WebSearchResult", "WebSearchResult")
                        .WithMany("ReportResults")
                        .HasForeignKey("WebSearchResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");

                    b.Navigation("WebSearchResult");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.ReportSection", b =>
                {
                    b.HasOne("Alfanar.MarketIntel.Domain.Entities.FinancialReport", "FinancialReport")
                        .WithMany("Sections")
                        .HasForeignKey("FinancialReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinancialReport");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.SmartAlert", b =>
                {
                    b.HasOne("Alfanar.MarketIntel.Domain.Entities.FinancialReport", "FinancialReport")
                        .WithMany()
                        .HasForeignKey("FinancialReportId");

                    b.Navigation("FinancialReport");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.TenderAiAnalysis", b =>
                {
                    b.HasOne("Alfanar.MarketIntel.Domain.Entities.TenderVersion", "TenderVersion")
                        .WithMany()
                        .HasForeignKey("TenderVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TenderVersion");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.TenderAuditRaw", b =>
                {
                    b.HasOne("Alfanar.MarketIntel.Domain.Entities.TenderSource", "Source")
                        .WithMany("AuditRawRecords")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.TenderAuthority", b =>
                {
                    b.HasOne("Alfanar.MarketIntel.Domain.Entities.TenderCountry", "Country")
                        .WithMany("Authorities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.TenderCapabilityGap", b =>
                {
                    b.HasOne("Alfanar.MarketIntel.Domain.Entities.TenderVersion", "TenderVersion")
                        .WithMany()
                        .HasForeignKey("TenderVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TenderVersion");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.TenderDocument", b =>
                {
                    b.HasOne("Alfanar.MarketIntel.Domain.Entities.TenderNotice", "TenderNotice")
                        .WithMany("Documents")
                        .HasForeignKey("TenderNoticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TenderNotice");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.TenderIngestionRun", b =>
                {
                    b.HasOne("Alfanar.MarketIntel.Domain.Entities.TenderSource", "Source")
                        .WithMany("IngestionRuns")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.TenderNotice", b =>
                {
                    b.HasOne("Alfanar.MarketIntel.Domain.Entities.TenderAuthority", "Authority")
                        .WithMany("Notices")
                        .HasForeignKey("AuthorityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Alfanar.MarketIntel.Domain.Entities.TenderCountry", "Country")
                        .WithMany("Notices")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Alfanar.MarketIntel.Domain.Entities.TenderVersion", "CurrentVersion")
                        .WithMany()
                        .HasForeignKey("CurrentVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Alfanar.MarketIntel.Domain.Entities.TenderSource", "Source")
                        .WithMany("Notices")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Authority");

                    b.Navigation("Country");

                    b.Navigation("CurrentVersion");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.TenderNotificationLog", b =>
                {
                    b.HasOne("Alfanar.MarketIntel.Domain.Entities.TenderNotificationRule", "Rule")
                        .WithMany("NotificationLogs")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Alfanar.MarketIntel.Domain.Entities.TenderNotice", "TenderNotice")
                        .WithMany("NotificationLogs")
                        .HasForeignKey("TenderNoticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alfanar.MarketIntel.Domain.Entities.TenderVersion", "TenderVersion")
                        .WithMany("NotificationLogs")
                        .HasForeignKey("TenderVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rule");

                    b.Navigation("TenderNotice");

                    b.Navigation("TenderVersion");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.TenderScore", b =>
                {
                    b.HasOne("Alfanar.MarketIntel.Domain.Entities.TenderVersion", "TenderVersion")
                        .WithMany()
                        .HasForeignKey("TenderVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TenderVersion");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.TenderVersion", b =>
                {
                    b.HasOne("Alfanar.MarketIntel.Domain.Entities.TenderNotice", "TenderNotice")
                        .WithMany("Versions")
                        .HasForeignKey("TenderNoticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TenderNotice");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.WebSearchResult", b =>
                {
                    b.HasOne("Alfanar.MarketIntel.Domain.Entities.KeywordMonitor", "KeywordMonitor")
                        .WithMany("WebSearchResults")
                        .HasForeignKey("KeywordMonitorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("KeywordMonitor");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.CompanyContactInfo", b =>
                {
                    b.Navigation("CompanyOffices");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.Competitor", b =>
                {
                    b.Navigation("Mentions");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.FinancialReport", b =>
                {
                    b.Navigation("Analysis");

                    b.Navigation("FinancialReportTags");

                    b.Navigation("RelatedArticles");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.IntelligenceReport", b =>
                {
                    b.Navigation("ReportResults");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.KeywordMonitor", b =>
                {
                    b.Navigation("WebSearchResults");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.NewsArticle", b =>
                {
                    b.Navigation("NewsArticleTags");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.RssFeed", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.Tag", b =>
                {
                    b.Navigation("FinancialReportTags");

                    b.Navigation("NewsArticleTags");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.TechnologyReport", b =>
                {
                    b.Navigation("ReportResults");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.TenderAuthority", b =>
                {
                    b.Navigation("Notices");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.TenderCountry", b =>
                {
                    b.Navigation("Authorities");

                    b.Navigation("Notices");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.TenderNotice", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("NotificationLogs");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.TenderNotificationRule", b =>
                {
                    b.Navigation("NotificationLogs");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.TenderSource", b =>
                {
                    b.Navigation("AuditRawRecords");

                    b.Navigation("IngestionRuns");

                    b.Navigation("Notices");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.TenderVersion", b =>
                {
                    b.Navigation("NotificationLogs");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.WebSearchResult", b =>
                {
                    b.Navigation("ReportResults");
                });
#pragma warning restore 612, 618
        }
    }
}
