// <auto-generated />
using System;
using Alfanar.MarketIntel.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Alfanar.MarketIntel.Infrastructure.Migrations
{
    [DbContext(typeof(MarketIntelDbContext))]
    [Migration("20260201095332_AddWebsiteToCompanyContactInfo")]
    partial class AddWebsiteToCompanyContactInfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.CompanyContactInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("HeadquartersAddressLine1")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HeadquartersAddressLine2")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HeadquartersCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HeadquartersCountry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HeadquartersCountryCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("HeadquartersLandmark")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HeadquartersPoBox")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HeadquartersPostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MainPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneAvailabilityDays")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneAvailabilityHours")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneAvailabilityTimezone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SalesEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SupportEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TollFreePhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Company")
                        .IsUnique();

                    b.ToTable("CompanyContactInfo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Company = "alfanar",
                            CreatedAt = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            HeadquartersAddressLine1 = "Al-Nafl - Northern Ring Road",
                            HeadquartersAddressLine2 = "Between Exits 5 & 6",
                            HeadquartersCity = "Riyadh",
                            HeadquartersCountry = "Kingdom of Saudi Arabia",
                            HeadquartersCountryCode = "KSA",
                            HeadquartersLandmark = "Near King Abdulaziz Center for National Dialogue",
                            HeadquartersPoBox = "P.O. Box 301",
                            HeadquartersPostalCode = "11411",
                            MainPhone = "+966 573786035",
                            PhoneAvailabilityDays = "Mon-Fri",
                            PhoneAvailabilityHours = "9AM-6PM",
                            PhoneAvailabilityTimezone = "EST",
                            SalesEmail = "sales@alfanar.com",
                            SupportEmail = "support@alfanar.com",
                            TollFreePhone = "800-124-1333",
                            UpdatedAt = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.CompanyOffice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Building")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BuildingNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CompanyContactInfoId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Floor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OfficeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PoBox")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Street")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Tower")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Country");

                    b.HasIndex("CompanyContactInfoId", "Region");

                    b.ToTable("CompanyOffices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = "alfanar Industrial City",
                            Building = "Sales and Marketing Building",
                            CompanyContactInfoId = 1,
                            Country = "Saudi Arabia",
                            CreatedAt = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            OfficeType = "Sales and Marketing",
                            Region = "Saudi Arabia",
                            UpdatedAt = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            City = "Madrid",
                            CompanyContactInfoId = 1,
                            Country = "Spain",
                            CreatedAt = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            OfficeType = "Regional Office",
                            Region = "Europe",
                            UpdatedAt = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CompanyContactInfoId = 1,
                            CompanyName = "alfanar Electrical Systems LLC",
                            Country = "United Arab Emirates",
                            CreatedAt = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            OfficeType = "Subsidiary",
                            Region = "UAE",
                            UpdatedAt = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Area = "DLF Cybercity, Phase-3",
                            BuildingNumber = "Building No. 5",
                            City = "Gurgaon",
                            CompanyContactInfoId = 1,
                            Country = "India",
                            CreatedAt = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Floor = "15th Floor",
                            OfficeType = "Regional Office",
                            Region = "India",
                            Tower = "Tower B",
                            UpdatedAt = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Area = "Sheraton Al Matar",
                            City = "Cairo",
                            CompanyContactInfoId = 1,
                            Country = "Egypt",
                            CreatedAt = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "El Nozha",
                            OfficeType = "Regional Office",
                            PoBox = "P.O. Box 11736",
                            Region = "Egypt",
                            Street = "181 El-Orouba St",
                            UpdatedAt = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.ContactFormSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RespondedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ResponseMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("IsRead");

                    b.HasIndex("Status");

                    b.HasIndex("SubmittedAt");

                    b.ToTable("ContactFormSubmissions");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.FinancialMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Change")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ChangePercent")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("float");

                    b.Property<DateTime>("ExtractedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExtractionMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("FinancialReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MetricType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Period")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("PreviousValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("SourceText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Value")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("FinancialReportId");

                    b.HasIndex("MetricType");

                    b.ToTable("FinancialMetrics");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.FinancialReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DownloadUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FiscalQuarter")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("FiscalYear")
                        .HasColumnType("int");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PageCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ProcessedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("RequiredOcr")
                        .HasColumnType("bit");

                    b.Property<string>("Sector")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyName");

                    b.HasIndex("IsProcessed");

                    b.HasIndex("ProcessingStatus");

                    b.HasIndex("PublishedDate");

                    b.HasIndex("ReportType");

                    b.HasIndex("SourceUrl")
                        .IsUnique();

                    b.HasIndex("FiscalYear", "FiscalQuarter");

                    b.ToTable("FinancialReports");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.NewsArticle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BodyText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("ClassificationConfidence")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ProcessedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PublishedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("RelatedFinancialReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RssFeedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("PublishedUtc");

                    b.HasIndex("RelatedFinancialReportId");

                    b.HasIndex("RssFeedId");

                    b.HasIndex("Source");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.HasIndex("Category", "Region");

                    b.ToTable("NewsArticles");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.NewsArticleTag", b =>
                {
                    b.Property<Guid>("NewsArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("NewsArticleId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("NewsArticleTags");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.ReportAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AiModel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("AnalysisConfidence")
                        .HasColumnType("float");

                    b.Property<string>("CompetitivePosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExecutiveSummary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinancialMetrics")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FinancialReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InvestmentThesis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeyHighlights")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarketOutlook")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ProcessingTimeMs")
                        .HasColumnType("bigint");

                    b.Property<string>("RelatedEntities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RiskFactors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SentimentLabel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("SentimentScore")
                        .HasColumnType("float");

                    b.Property<string>("StrategicInitiatives")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TokensUsed")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("FinancialReportId")
                        .IsUnique();

                    b.HasIndex("SentimentScore");

                    b.ToTable("ReportAnalyses");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.ReportSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<double?>("ExtractionConfidence")
                        .HasColumnType("float");

                    b.Property<Guid>("FinancialReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("KeyDataPoints")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("PageNumbers")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SectionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("FinancialReportId");

                    b.HasIndex("FinancialReportId", "OrderIndex");

                    b.ToTable("ReportSections");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.RssFeed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastETag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastFetchedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModified")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("RssFeeds");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.SmartAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AcknowledgedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ActualValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FinancialReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("ThresholdValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TriggerKeywords")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TriggerMetric")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AlertType");

                    b.HasIndex("CompanyName");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FinancialReportId");

                    b.HasIndex("IsAcknowledged");

                    b.HasIndex("Severity");

                    b.ToTable("SmartAlerts");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.CompanyOffice", b =>
                {
                    b.HasOne("Alfanar.MarketIntel.Domain.Entities.CompanyContactInfo", "CompanyContactInfo")
                        .WithMany("CompanyOffices")
                        .HasForeignKey("CompanyContactInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyContactInfo");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.FinancialMetric", b =>
                {
                    b.HasOne("Alfanar.MarketIntel.Domain.Entities.FinancialReport", "FinancialReport")
                        .WithMany()
                        .HasForeignKey("FinancialReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinancialReport");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.NewsArticle", b =>
                {
                    b.HasOne("Alfanar.MarketIntel.Domain.Entities.FinancialReport", "RelatedFinancialReport")
                        .WithMany("RelatedArticles")
                        .HasForeignKey("RelatedFinancialReportId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Alfanar.MarketIntel.Domain.Entities.RssFeed", "RssFeed")
                        .WithMany("Articles")
                        .HasForeignKey("RssFeedId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RelatedFinancialReport");

                    b.Navigation("RssFeed");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.NewsArticleTag", b =>
                {
                    b.HasOne("Alfanar.MarketIntel.Domain.Entities.NewsArticle", "NewsArticle")
                        .WithMany("NewsArticleTags")
                        .HasForeignKey("NewsArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alfanar.MarketIntel.Domain.Entities.Tag", "Tag")
                        .WithMany("NewsArticleTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewsArticle");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.ReportAnalysis", b =>
                {
                    b.HasOne("Alfanar.MarketIntel.Domain.Entities.FinancialReport", "FinancialReport")
                        .WithOne("Analysis")
                        .HasForeignKey("Alfanar.MarketIntel.Domain.Entities.ReportAnalysis", "FinancialReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinancialReport");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.ReportSection", b =>
                {
                    b.HasOne("Alfanar.MarketIntel.Domain.Entities.FinancialReport", "FinancialReport")
                        .WithMany("Sections")
                        .HasForeignKey("FinancialReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinancialReport");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.SmartAlert", b =>
                {
                    b.HasOne("Alfanar.MarketIntel.Domain.Entities.FinancialReport", "FinancialReport")
                        .WithMany()
                        .HasForeignKey("FinancialReportId");

                    b.Navigation("FinancialReport");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.CompanyContactInfo", b =>
                {
                    b.Navigation("CompanyOffices");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.FinancialReport", b =>
                {
                    b.Navigation("Analysis");

                    b.Navigation("RelatedArticles");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.NewsArticle", b =>
                {
                    b.Navigation("NewsArticleTags");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.RssFeed", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("Alfanar.MarketIntel.Domain.Entities.Tag", b =>
                {
                    b.Navigation("NewsArticleTags");
                });
#pragma warning restore 612, 618
        }
    }
}
